"""
Build cumulative ICR curves from saved per-example metrics.

The script reads results generated by Prueba/run_metrics.py or the original
run_metrics.py. It does not rerun attacks or load models.

Example:
    python Prueba/plot_icr_cum.py ^
        --model B30-Shield ^
        --attack PGDLInf_attack ^
        --seed 1 ^
        --max_eps 0.4 ^
        --step_size 0.025
"""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path

import numpy as np


SCRIPT_DIR = Path(__file__).resolve().parent
ROOT = SCRIPT_DIR.parent
DEFAULT_RESULTS_ROOT = ROOT / "resultsTFG" / "runs_v1"
DEFAULT_OUT_DIR = SCRIPT_DIR / "ICR_cum"
DEFAULT_DATASET = "mnist"
DEFAULT_THREAT = "Linf"


def format_float_for_filename(value: float | None) -> str:
    if value is None:
        return "all"
    return f"{value:g}".replace(".", "e").replace("-", "m")


def safe_name(value: str) -> str:
    return value.replace("/", "_").replace("\\", "_").replace(":", "_")


def resolve_run_dir(
    results_root: Path,
    dataset: str,
    threat: str,
    attack: str,
    model: str,
    seed: int,
    run_id: str | None,
) -> Path:
    seed_dir = results_root / dataset / threat / attack / model / f"seed={seed}"
    if run_id is not None:
        run_dir = seed_dir / f"run_id={run_id}"
        if not run_dir.exists():
            raise FileNotFoundError(f"Run directory not found: {run_dir}")
        return run_dir

    candidates = [
        path
        for path in seed_dir.glob("run_id=*")
        if (path / "per_example_metrics.npz").exists()
        and (path / "per_example_correct.npz").exists()
    ]
    if not candidates:
        raise FileNotFoundError(
            "No runs with per_example_metrics.npz and per_example_correct.npz "
            f"found under {seed_dir}"
        )
    return max(candidates, key=lambda path: path.stat().st_mtime)


def load_optional_json(path: Path) -> dict:
    if not path.exists():
        return {}
    with path.open("r", encoding="utf-8") as fh:
        return json.load(fh)


def select_eps_columns(
    eps: np.ndarray,
    max_eps: float | None,
    step_size: float | None,
    atol: float = 1e-7,
) -> np.ndarray:
    eps = np.asarray(eps, dtype=np.float64)
    upper = float(eps[-1]) if max_eps is None else float(max_eps)

    if step_size is None:
        idx = np.flatnonzero(eps <= upper + atol)
        if idx.size == 0:
            raise ValueError(f"No epsilon values found <= max_eps={upper}.")
        return idx

    if step_size <= 0:
        raise ValueError(f"step_size must be > 0, got {step_size}.")

    expected = np.arange(0.0, upper + atol, float(step_size), dtype=np.float64)
    selected = []
    missing = []
    for value in expected:
        matches = np.flatnonzero(np.isclose(eps, value, atol=atol, rtol=0.0))
        if matches.size:
            selected.append(int(matches[0]))
        else:
            missing.append(float(value))

    if missing:
        available = ", ".join(f"{value:g}" for value in eps.tolist())
        requested = ", ".join(f"{value:g}" for value in missing[:10])
        raise ValueError(
            "The requested epsilon grid is not present in the saved run. "
            f"Missing values: {requested}. Available eps: {available}"
        )

    return np.asarray(selected, dtype=np.int64)


def compute_cumulative_icr(
    m_proto: np.ndarray,
    m_pred: np.ndarray,
    clean_correct_mask: np.ndarray,
) -> dict[str, np.ndarray | int]:
    if m_proto.shape != m_pred.shape:
        raise ValueError(
            "m_proto and m_pred must have the same shape, "
            f"got {m_proto.shape} and {m_pred.shape}."
        )
    if clean_correct_mask.ndim != 1 or clean_correct_mask.shape[0] != m_proto.shape[0]:
        raise ValueError(
            "clean_correct_mask must have one entry per sample, "
            f"got {clean_correct_mask.shape} for {m_proto.shape[0]} samples."
        )

    instant = (m_proto < 0.0) & (m_pred > 0.0)
    cumulative = np.maximum.accumulate(instant, axis=1)

    clean_mask = clean_correct_mask.astype(bool)
    if clean_mask.any():
        icr_cum = cumulative[clean_mask].mean(axis=0)
        icr_inst = instant[clean_mask].mean(axis=0)
        n_cum = cumulative[clean_mask].sum(axis=0)
        n_inst = instant[clean_mask].sum(axis=0)
    else:
        icr_cum = np.full(m_proto.shape[1], np.nan, dtype=np.float64)
        icr_inst = np.full(m_proto.shape[1], np.nan, dtype=np.float64)
        n_cum = np.zeros(m_proto.shape[1], dtype=np.int64)
        n_inst = np.zeros(m_proto.shape[1], dtype=np.int64)

    return {
        "icr_cum": icr_cum.astype(np.float64),
        "icr_instant": icr_inst.astype(np.float64),
        "icr_cum_all": cumulative.mean(axis=0).astype(np.float64),
        "icr_instant_all": instant.mean(axis=0).astype(np.float64),
        "n_cum": n_cum.astype(np.int64),
        "n_instant": n_inst.astype(np.int64),
        "n_cum_all": cumulative.sum(axis=0).astype(np.int64),
        "n_instant_all": instant.sum(axis=0).astype(np.int64),
        "n_total": int(m_proto.shape[0]),
        "n_clean_correct": int(clean_mask.sum()),
    }


def write_csv(
    csv_path: Path,
    eps: np.ndarray,
    curves: dict[str, np.ndarray | int],
) -> None:
    csv_path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = [
        "epsilon",
        "icr_cum",
        "icr_instant",
        "icr_cum_all",
        "icr_instant_all",
        "n_cum",
        "n_instant",
        "n_cum_all",
        "n_instant_all",
        "n_clean_correct",
        "n_total",
    ]
    with csv_path.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames)
        writer.writeheader()
        for idx, epsilon in enumerate(eps):
            writer.writerow({
                "epsilon": float(epsilon),
                "icr_cum": float(curves["icr_cum"][idx]),
                "icr_instant": float(curves["icr_instant"][idx]),
                "icr_cum_all": float(curves["icr_cum_all"][idx]),
                "icr_instant_all": float(curves["icr_instant_all"][idx]),
                "n_cum": int(curves["n_cum"][idx]),
                "n_instant": int(curves["n_instant"][idx]),
                "n_cum_all": int(curves["n_cum_all"][idx]),
                "n_instant_all": int(curves["n_instant_all"][idx]),
                "n_clean_correct": int(curves["n_clean_correct"]),
                "n_total": int(curves["n_total"]),
            })


def write_plot(
    plot_path: Path,
    eps: np.ndarray,
    curves: dict[str, np.ndarray | int],
    model: str,
    attack: str,
    run_id: str,
    metadata: dict,
) -> None:
    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError as exc:
        raise ImportError(
            "matplotlib is required to create the ICR plot. Install it in the "
            "environment used to run this script."
        ) from exc

    plot_path.parent.mkdir(parents=True, exist_ok=True)

    plt.figure(figsize=(8, 6))
    plt.plot(eps, curves["icr_cum"], marker="o", label="ICR cumulative")
    plt.plot(
        eps,
        curves["icr_instant"],
        marker="x",
        linestyle="--",
        alpha=0.65,
        label="ICR per epsilon",
    )
    plt.xlabel("Epsilon")
    plt.ylabel("ICR")
    plt.ylim(0.0, 1.0)
    plt.grid(True, alpha=0.25)
    plt.legend()

    shield = metadata.get("shield") or {}
    attack_mode = shield.get("attack_mode") or shield.get("pgd_mode")
    mode_suffix = f" | {attack_mode}" if attack_mode else ""
    plt.title(
        "Cumulative ICR vs. Epsilon\n"
        f"Model: {model} | Attack: {attack}{mode_suffix} | Run: {run_id}"
    )
    plt.tight_layout()
    plt.savefig(plot_path, dpi=300)
    plt.close()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create cumulative ICR CSV and plot from saved metric runs."
    )
    parser.add_argument("--model", required=True, help="Model name, e.g. B30-Shield.")
    parser.add_argument("--attack", default="PGDLInf_attack", help="Attack name.")
    parser.add_argument("--seed", type=int, default=1)
    parser.add_argument(
        "--run_id",
        default=None,
        help="Run id without the run_id= prefix. Defaults to the latest run.",
    )
    parser.add_argument("--max_eps", type=float, default=None)
    parser.add_argument("--step_size", type=float, default=None)
    parser.add_argument("--dataset", default=DEFAULT_DATASET)
    parser.add_argument("--threat", default=DEFAULT_THREAT)
    parser.add_argument("--results_root", type=Path, default=DEFAULT_RESULTS_ROOT)
    parser.add_argument("--out_dir", type=Path, default=DEFAULT_OUT_DIR)
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    run_dir = resolve_run_dir(
        results_root=args.results_root,
        dataset=args.dataset,
        threat=args.threat,
        attack=args.attack,
        model=args.model,
        seed=args.seed,
        run_id=args.run_id,
    )
    run_id = run_dir.name.removeprefix("run_id=")

    metrics_path = run_dir / "per_example_metrics.npz"
    correct_path = run_dir / "per_example_correct.npz"
    metadata_path = run_dir / "metrics.json"

    metrics = np.load(metrics_path)
    correct = np.load(correct_path)
    metadata = load_optional_json(metadata_path)

    required = {"eps", "m_proto", "m_pred"}
    missing = required.difference(metrics.files)
    if missing:
        raise KeyError(
            f"{metrics_path} is missing required arrays: {', '.join(sorted(missing))}"
        )
    if "correct" not in correct.files:
        raise KeyError(f"{correct_path} is missing required array: correct")

    eps_idx = select_eps_columns(
        eps=metrics["eps"],
        max_eps=args.max_eps,
        step_size=args.step_size,
    )
    eps = metrics["eps"][eps_idx].astype(np.float64)
    m_proto = metrics["m_proto"][:, eps_idx]
    m_pred = metrics["m_pred"][:, eps_idx]
    correct_matrix = correct["correct"][:, eps_idx]
    clean_correct_mask = correct_matrix[:, 0].astype(bool)

    curves = compute_cumulative_icr(
        m_proto=m_proto,
        m_pred=m_pred,
        clean_correct_mask=clean_correct_mask,
    )

    tag = (
        f"{safe_name(args.attack)}_{safe_name(args.model)}_"
        f"seed{args.seed}_run{safe_name(run_id)}_"
        f"maxeps{format_float_for_filename(args.max_eps)}_"
        f"step{format_float_for_filename(args.step_size)}"
    )
    csv_path = args.out_dir / f"{tag}_icr_cum.csv"
    plot_path = args.out_dir / f"{tag}_icr_cum.jpg"

    write_csv(csv_path, eps, curves)
    write_plot(
        plot_path=plot_path,
        eps=eps,
        curves=curves,
        model=args.model,
        attack=args.attack,
        run_id=run_id,
        metadata=metadata,
    )

    print(f"Run directory: {run_dir}")
    print(f"CSV saved to: {csv_path}")
    print(f"Plot saved to: {plot_path}")
    print(f"Final cumulative ICR: {curves['icr_cum'][-1]:.6f}")
    print(f"Final all-sample cumulative ICR: {curves['icr_cum_all'][-1]:.6f}")


if __name__ == "__main__":
    main()
